# Generated by Django 2.0 on 2018-12-15 03:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Works',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='作品名称')),
                ('tag', models.CharField(max_length=10, verbose_name='作品标签')),
                ('love_nums', models.IntegerField(default=0, verbose_name='点赞数')),
                ('fav_nums', models.IntegerField(default=0, verbose_name='收藏数')),
                ('download_nums', models.IntegerField(default=0, verbose_name='下载数')),
                ('image', models.ImageField(upload_to='works/%Y/%m', verbose_name='作品')),
                ('desc', models.CharField(max_length=1500, verbose_name='说明')),
                ('add_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': '作品',
                'verbose_name_plural': '作品',
            },
        ),
    ]
