# Generated by Django 2.0 on 2019-04-25 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='open_id',
            field=models.CharField(default='', max_length=100, verbose_name='OPENID'),
        ),
    ]
