# Generated by Django 2.0 on 2019-04-25 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userprofile_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='focus_cities',
            field=models.TextField(default='[]'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='focus_constellations',
            field=models.TextField(default='[]'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='focus_stocks',
            field=models.TextField(default='[]'),
        ),
    ]
