# Generated by Django 2.0 on 2019-05-04 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20190425_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(default='image/default.png', max_length=500, upload_to='image/%Y/%m', verbose_name='头像'),
        ),
    ]
